### ISSUE TITLE
error while importing text file for startURLS

### ISSUE THREAD

**Issue by arfizato** [EPCSHT/walmart-scraper#3]
Hello, I'm trying to use your product but I ran into an issue where if I try to import a CSV file containing my URLs it will give me this typeError
```
2022-09-15T17:21:32.765Z ACTOR: Pulling Docker image from repository.
2022-09-15T17:21:34.651Z ACTOR: Creating Docker container.
2022-09-15T17:21:35.157Z ACTOR: Starting Docker container.
2022-09-15T17:21:38.484Z INFO  System info {"apifyVersion":"3.0.2","apifyClientVersion":"2.6.0","osType":"Linux","nodeVersion":"v16.17.0"}
2022-09-15T17:21:38.490Z INFO  PHASE -- STARTING ACTOR.
2022-09-15T17:21:38.799Z INFO  PHASE -- SETTING UP CRAWLER.
2022-09-15T17:21:39.165Z INFO  CRAWLER STARTED.
2022-09-15T17:21:39.167Z file:///home/myuser/src/tools.js:20
2022-09-15T17:21:39.169Z         if (url.includes('/search')) {
2022-09-15T17:21:39.172Z                 ^
2022-09-15T17:21:39.175Z 
2022-09-15T17:21:39.176Z TypeError: Cannot read properties of undefined (reading 'includes')
2022-09-15T17:21:39.177Z     at file:///home/myuser/src/tools.js:20:17
2022-09-15T17:21:39.180Z     at Array.map (<anonymous>)
2022-09-15T17:21:39.184Z     at mapStartUrls (file:///home/myuser/src/tools.js:15:22)
2022-09-15T17:21:39.187Z     at Object.getSources (file:///home/myuser/src/tools.js:77:29)
2022-09-15T17:21:39.188Z     at file:///home/myuser/src/main.js:81:27
2022-09-15T17:21:39.188Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)

```
![image_2022-09-15_182919807](https://user-images.githubusercontent.com/33662900/190471395-136b7fff-1f39-463e-86f7-fea4624b9026.png)

**Comment by tugkan** [comment]
Hey @arfizato !

Thank you very much for reaching out. Unfortunately the actor doesn't support the file upload right now. This is why you are having this problem. If you can provide all the links as a list inside, it will work properly.

Best

**Comment by arfizato** [comment]
@tugkan the list is dynamic which is why manual input is not a solution

**Comment by arfizato** [comment]
is there any way i can get my hands on the code or is there any way where I can write some of the code it runs ?

**Comment by tugkan** [comment]
Unfortunately, the source code is not public. However; all the actors can be run via Apify's API. Meaning that you can read the file dynamically and call the actor via API with the `startUrls`. I hope that helps.

Best

**Comment by arfizato** [comment]
thank you.

**Comment by arfizato** [comment]
@tugkan I could not find a useful resource the [API V2 ](https://docs.apify.com/api/v2#/reference/actors/run-actor-synchronously/with-input) was not very helpful.

**Comment by tugkan** [comment]
Hey @arfizato !

You should call this endpoint (POST) with your own API token `https://api.apify.com/v2/acts/epcsht~walmart-scraper/run-sync?token=[API_TOKEN]` and provide the payload (body) as the input for the actor.

Best

**Comment by arfizato** [comment]
Hey @tugkan and thank you for your patience 
I ran exactly that as you see below but I'm still running into issues 
```python
from urllib.request import Request, urlopen
values = """
{
    "endPage": 1,
    "extendOutputFunction": "($) => {\n    const result = {};\n    // Uncomment to add a title to the output\n    // result.title = $('title').text().trim();\n\n    return result;\n}",
    "maxItems": 50,
    "outputFilterFunction": "(object) => ({...object})",
    "proxy": {
        "useApifyProxy": true
    },
    "startUrls": [
        {
            "url": "Link_Example"
        },
        {
            "url": "Link_Example"
        },
        {
            "url": "Link_Example"
        },
        {
            "url": "Link_Example"
        },
        {
            "url": "Link_Example"
        }
    ]
}
"""

headers = {
'Content-Type': 'application/json'
}
url= 'https://api.apify.com/v2/acts/epcsht~walmart-scraper/runs?token=[APÏ_TOKEN]'


request = Request(url , data=values, headers=headers)

response_body = urlopen(request).read()
print (response_body)
```

**Comment by tugkan** [comment]
Hey @arfizato ! 

Unfortunately, Python is not our strong side. That's why we are not 100% sure what the problem might be with the code above. However, if you can share the response from the API, we might provide some ideas on top of it.

Best

**Comment by arfizato** [comment]
Hello @tugkan, 
no problem at all I had enough time to work on the code and fixed it. 
here it is if there's anyone running into the same issue and might need it 
```python
from urllib.request import Request, urlopen
import json
import pandas as pd 

f= open("data.json")
values = json.load(f)

headers = { 'Content-Type': 'application/json' }


sheetId= "[sheetID]"
sheetName="test"
url = f"https://docs.google.com/spreadsheets/d/{sheetId}/gviz/tq?tqx=out:csv&sheet={sheetName}"

urlSeries= pd.read_csv(url)["URL"]
for url in urlSeries:
    values["startUrls"].append({"url":url})
    print(len(values["startUrls"]),values["startUrls"][-1])


url= 'https://api.apify.com/v2/acts/epcsht~walmart-scraper/runs?token=[TOKEN]'

req = Request(url , data=bytes(json.dumps(values), encoding="utf-8"), headers=headers)

response_body = urlopen(req).read()
print (response_body)
```
But if you don't mind helping me out with something I tried creating an actor to execute this block of code but I got this error 
```
2022-09-15T23:05:40.381Z ACTOR: Pulling Docker image from repository.
2022-09-15T23:05:43.827Z ACTOR: Creating Docker container.
2022-09-15T23:05:44.326Z ACTOR: Starting Docker container.
2022-09-15T23:05:45.810Z 1 {'url': 'https://www.walmart.com/ip/BAZIC-Double-Sided-Tape-1-X-36-Yard-1296-1-Pack/184424048'}
2022-09-15T23:05:45.812Z 2 {'url': 'https://www.walmart.com/ip/BAZIC-Small-Spiral-Bound-Notebook-5-x7-120-Sheets-Assorted-Color-4-Pack/23331678?athcpid=23331678&athpgid=sellerpage_184424048&athcgid=null&athznid=mtsi&athieid=v0&athstid=CS020&athguid=aqRX0L4HqxyDZsuGO1Qk5wi2D2_0eM1fE596&athancid=null&athena=true&selectedSellerId=101096911'}
2022-09-15T23:05:45.812Z 3 {'url': 'https://www.walmart.com/ip/Gold-Series-New-Lengths-Root-Stimulating-Shampoo-Apricot-Oil-Green-Tea-Cleanses-Awakens-Natural-Textured-Curly-Coily-Hair-Sulfate-Free-Paraben-Free-D/456874544?athcpid=456874544&athpgid=sellerpage_184424048&athcgid=null&athznid=mtsi&athieid=v0&athstid=CS020&athguid=aqRX0L4HqxyDZsuGO1Qk5wi2D2_0eM1fE596&athancid=null&athena=true&selectedSellerId=101096911'}
2022-09-15T23:05:45.813Z 4 {'url': 'https://www.walmart.com/ip/Essential-Oxygen-Food-Grade-Hydrogen-Peroxide-16-Oz/26957197?athcpid=26957197&athpgid=sellerpage_184424048&athcgid=null&athznid=mtsi&athieid=v0&athstid=CS020&athguid=aqRX0L4HqxyDZsuGO1Qk5wi2D2_0eM1fE596&athancid=null&athena=true&selectedSellerId=101096911'}
2022-09-15T23:05:45.813Z 5 {'url': 'https://www.walmart.com/ip/Cotton-Mouth-Candy-Sour-Mix-Bag-3-3-oz/320168518?athcpid=320168518&athpgid=sellerpage_184424048&athcgid=null&athznid=mtsi&athieid=v0&athstid=CS020&athguid=aqRX0L4HqxyDZsuGO1Qk5wi2D2_0eM1fE596&athancid=null&athena=true&selectedSellerId=101096911'}
2022-09-15T23:05:45.852Z Traceback (most recent call last):
2022-09-15T23:05:45.853Z   File "/usr/src/app/main.py", line 38, in <module>
2022-09-15T23:05:45.854Z     response_body = urlopen(req).read()
2022-09-15T23:05:45.854Z   File "/usr/local/lib/python3.9/urllib/request.py", line 214, in urlopen
2022-09-15T23:05:45.855Z     return opener.open(url, data, timeout)
2022-09-15T23:05:45.855Z   File "/usr/local/lib/python3.9/urllib/request.py", line 523, in open
2022-09-15T23:05:45.856Z     response = meth(req, response)
2022-09-15T23:05:45.856Z   File "/usr/local/lib/python3.9/urllib/request.py", line 632, in http_response
2022-09-15T23:05:45.857Z     response = self.parent.error(
2022-09-15T23:05:45.857Z   File "/usr/local/lib/python3.9/urllib/request.py", line 561, in error
2022-09-15T23:05:45.858Z     return self._call_chain(*args)
2022-09-15T23:05:45.858Z   File "/usr/local/lib/python3.9/urllib/request.py", line 494, in _call_chain
2022-09-15T23:05:45.859Z     result = func(*args)
2022-09-15T23:05:45.860Z   File "/usr/local/lib/python3.9/urllib/request.py", line 641, in http_error_default
2022-09-15T23:05:45.860Z     raise HTTPError(req.full_url, code, msg, hdrs, fp)
2022-09-15T23:05:45.861Z urllib.error.HTTPError: HTTP Error 402: Payment Required
```
did you ever run into this? do you know if it's allowed/possible? do you know what I can do to fix it? 
I'm basically trying to create this factor so I can schedule it to run your actor periodically using the input I want it to

**Comment by tugkan** [comment]
Hey @arfizato !

The actor on Apify is paid. This means that you have to pay a certain amount to use and put some credits inside the platform to run it. As far as I understand you have fixed the code to hit the API but you need to pay for it.

Hope that helps,
Best
